version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: yarn run dev
    environment:
      NODE_ENV: development
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
