version: '3'
# for develop environment
services:
  # backend server
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: yarn run dev
    environment:
      NODE_ENV: development
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
  # MySQL
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3308:3306
  # frontend react app
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: yarn run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
